name: CI

on:
  - push
  - pull_request

permissions: {}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        arch:
          - x64
        node:
          - 16
          - 18
          - 19
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    steps:
      - name: Configure npm time machine registry
        run: npm config set registry https://:2022-11-06T20%3A02%3A55.232000Z@time-machines-npm.sealsecurity.io/
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.arch }}
      - run: npm config set registry https://time-machines-npm.sealsecurity.io/
      - run: npm config set //time-machines-npm.sealsecurity.io/:_authToken=2022-11-06T00:00:00.000000Z
      - run: npm install
      - run: npm test
